[main]
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=powersave-bazzite
balanced=balanced-bazzite
performance=throughput-performance-bazzite

[battery]
balanced=balanced-battery-bazzite
power-saver=powersave-battery-bazzite
